name: Deploy Razma Portfolio

on:
  push:
    branches:
      - main

concurrency:
  group: production
  cancel-in-progress: true

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Verify TypeScript
        run: npm run lint

      - name: Build Application
        run: npm run build

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          protocol: ftp
          port: 21

          local-dir: ./

          server-dir: razma-portfolio/

          dangerous-clean-slate: false

          exclude: |
            **/.git*
            **/.github/**
            **/.deployignore
            **/node_modules/**
            **/.env
            **/.env.*
            **/docs/**
            **/*.log
            **/.vscode/**